src/main/java/com/epris/homepage/activity/award_info/domain/AwardInfo.java
src/main/java/com/epris/homepage/activity/corporate_project/domain/CorporateProject.java
src/main/java/com/epris/homepage/activity/corporate_project/domain/CorporateProjectImage.java
src/main/java/com/epris/homepage/activity/network/domain/Network.java
src/main/java/com/epris/homepage/activity/network/domain/NetworkType.java
src/main/java/com/epris/homepage/activity/project/domain/Project.java
src/main/java/com/epris/homepage/activity/session/domain/Session.java
src/main/java/com/epris/homepage/activity/session/domain/SessionImage.java
src/main/java/com/epris/homepage/activity/session/domain/SessionType.java
src/main/java/com/epris/homepage/eprian/corporate_logo/domain/CorporateLogo.java
src/main/java/com/epris/homepage/eprian/corporate_logo/domain/LogoType.java
src/main/java/com/epris/homepage/eprian/member/domain/Member.java
src/main/java/com/epris/homepage/eprian/member/domain/Num.java
src/main/java/com/epris/homepage/eprian/member/domain/Position.java
src/main/java/com/epris/homepage/generation/class_info/domain/ClassInfo.java
src/main/java/com/epris/homepage/generation/greeting_card/domain/GreetingCard.java
src/main/java/com/epris/homepage/recruitment/domain/Recruitment.java

feat: 엔티티 생성

---

build.gradle
src/main/java/com/epris/homepage/global/Controller/FileController.java
src/main/java/com/epris/homepage/global/config/S3Config.java
src/main/java/com/epris/homepage/global/dto/FileRequestDto.java
src/main/java/com/epris/homepage/global/dto/FileResponseDto.java
src/main/java/com/epris/homepage/global/service/FileService.java

feat : pesigned url 이용 이미지 업로드 기능 개발

---

build.gradle
src/main/java/com/epris/homepage/HomepageApplication.java
src/main/java/com/epris/homepage/global/Controller/FileController.java
src/main/java/com/epris/homepage/global/config/S3Config.java
src/main/java/com/epris/homepage/global/dto/FileRequestDto.java
src/main/java/com/epris/homepage/global/service/FileService.java

- 인증 관련 오류 수정
- url 생성 시 파라미터 수정

fix : pesigned url 이용 이미지 업로드 기능 개발 오류 수정

---

src/main/java/com/epris/homepage/global/service/FileService.java

chore : 주석 수정

---

src/main/java/com/epris/homepage/global/config/S3Config.java
src/main/java/com/epris/homepage/global/controller/FileController.java
src/main/java/com/epris/homepage/global/exception/ErrorCode.java
src/main/java/com/epris/homepage/global/service/FileService.java

- S3에 올라가있는 객체를 삭제하는 기능 구현
- 주석 정리
- 사용하지 않는 메소드 삭제

feat : 파일 삭제 기능 구현

---

src/main/java/com/epris/homepage/activity/corporate_project/domain/CorporateProjectImage.java
src/main/java/com/epris/homepage/activity/corporate_project/repository/CorporateProjectLogoRespository.java
src/main/java/com/epris/homepage/activity/corporate_project/service/CorporateProjectService.java
src/main/java/com/epris/homepage/eprian/corporate_logo/controller/LogoController.java
src/main/java/com/epris/homepage/eprian/corporate_logo/domain/CorporateLogo.java
src/main/java/com/epris/homepage/eprian/corporate_logo/repository/LogoRepository.java
src/main/java/com/epris/homepage/eprian/corporate_logo/service/LogoService.java
src/main/java/com/epris/homepage/global/dto/ImageInfo.java
src/main/java/com/epris/homepage/global/dto/ImageRequestDto.java
src/main/java/com/epris/homepage/global/dto/ImageResponseDto.java
src/main/java/com/epris/homepage/global/dto/ImageUrl.java
src/main/java/com/epris/homepage/global/exception/ErrorCode.java
src/main/java/com/epris/homepage/global/service/FileService.java

- 기업 로고 업로드 기능
- 협력 기업
- 취업 기업

feat : 로고 수정/조회 기능 구현

---

src/main/java/com/epris/homepage/recruitment/controller/RecruitmentController.java
src/main/java/com/epris/homepage/recruitment/domain/Recruitment.java
src/main/java/com/epris/homepage/recruitment/dto/RecruitmentRequestDto.java
src/main/java/com/epris/homepage/recruitment/dto/RecruitmentResponseDto.java
src/main/java/com/epris/homepage/recruitment/repository/RecruitmentRepository.java
src/main/java/com/epris/homepage/recruitment/service/RecruitmentService.java

- 모집 정보 수정
- 모집 정보 조회
- 기존 문서와 이미지 삭제를 올바르게 구현했는지 확인 부탁드립니다!
- 내용을 업데이트 하여 이미지를 새로 저장할 때엔 따로 저장하는 로직을 구현하지 않아도 되는걸까요?
- #17

feat: 모집 정보 수정 및 조회

---

src/main/java/com/epris/homepage/generation/class_info/controller/ClassInfoController.java
src/main/java/com/epris/homepage/generation/class_info/service/ClassInfoService.java

- getClassInfo 메서드 접근제어자 public 설정
- 기존 운영진 이미지 삭제 로직 추가
- 기존 이미지 삭제를 올바르게 구현했는지 확인 부탁드립니다!
- 내용을 업데이트 하여 이미지를 새로 저장할 때엔 따로 저장하는 로직을 구현하지 않아도 되는걸까요?
- #14

fix: 기수 정보 업데이트 및 조회 오류 수정

---

src/main/java/com/epris/homepage/eprian/member/controller/MemberController.java
src/main/java/com/epris/homepage/eprian/member/domain/Member.java
src/main/java/com/epris/homepage/eprian/member/domain/Num.java
src/main/java/com/epris/homepage/eprian/member/dto/MemberNumResponseDto.java
src/main/java/com/epris/homepage/eprian/member/dto/MemberRequestDto.java
src/main/java/com/epris/homepage/eprian/member/dto/MemberResponseDto.java
src/main/java/com/epris/homepage/eprian/member/repository/MemberRepository.java
src/main/java/com/epris/homepage/eprian/member/repository/NumRepository.java
src/main/java/com/epris/homepage/eprian/member/service/MemberService.java
src/main/java/com/epris/homepage/global/exception/ErrorCode.java

- 학회원 정보 수정 기능
- 학회원 정보 삭제 기능
- 모든 기수별 학회원 목록 조회
- 운영진 학회원 목록 조회

feat : 학회원 수정/조회/삭제 기능 구현

---

src/main/java/com/epris/homepage/generation/greeting_card/controller/GreetingCardController.java
src/main/java/com/epris/homepage/generation/greeting_card/domain/GreetingCard.java
src/main/java/com/epris/homepage/generation/greeting_card/dto/GreetingCardRequestDto.java
src/main/java/com/epris/homepage/generation/greeting_card/dto/GreetingCardResponseDto.java
src/main/java/com/epris/homepage/generation/greeting_card/repository/GreetingCardRepository.java
src/main/java/com/epris/homepage/generation/greeting_card/service/GreetingCardService.java

- 그리팅 카드 생성
- 그리팅 카드 수정
- 그리팅 카드 삭제
- 그리팅 카드 목록 조회
- #20

feat: 그리팅 카드 CRUD

---

src/main/java/com/epris/homepage/eprian/member/controller/MemberController.java
src/main/java/com/epris/homepage/eprian/member/repository/MemberRepository.java
src/main/java/com/epris/homepage/eprian/member/service/MemberService.java

- 현재 활동중인 학회원 목록 조회 기능
- 기수별 수료 학회원 목록 조회 기능

feat : 학회원 목록 조회 기능 구현

---

src/main/java/com/epris/homepage/activity/project/controller/ProjectController.java
src/main/java/com/epris/homepage/activity/project/domain/Project.java
src/main/java/com/epris/homepage/activity/project/dto/ProjectRequestDto.java
src/main/java/com/epris/homepage/activity/project/dto/ProjectResponseDto.java
src/main/java/com/epris/homepage/activity/project/repository/ProjectRepository.java
src/main/java/com/epris/homepage/activity/project/service/ProjectService.java

- 프로젝트 생성
- 프로젝트 수정
- 프로젝트 삭제
- 프로젝트 목록 조회
- #21

feat: 프로젝트 CRUD

---

src/main/java/com/epris/homepage/activity/session/dto/SessionRequestDto.java
src/main/java/com/epris/homepage/activity/session/service/SessionService.java

- 세션 수정 요청 시 deleteImageUrl을 받지 않도록 수정

refactor : dto 수정

---

src/main/java/com/epris/homepage/activity/award_info/controller/AwardInfoController.java
src/main/java/com/epris/homepage/activity/award_info/domain/AwardInfo.java
src/main/java/com/epris/homepage/activity/award_info/dto/AwardInfoResponseDto.java
src/main/java/com/epris/homepage/activity/award_info/dto/AwardRequestDto.java
src/main/java/com/epris/homepage/activity/award_info/repository/AwardInfoRepository.java
src/main/java/com/epris/homepage/activity/award_info/service/AwardInfoService.java

feat : 수상 내역 수정 / 조회 기능

---

build.gradle
src/main/java/com/epris/homepage/admin/controller/AdminController.java
src/main/java/com/epris/homepage/admin/controller/TokenController.java
src/main/java/com/epris/homepage/admin/domain/Admin.java
src/main/java/com/epris/homepage/admin/domain/RefreshToken.java
src/main/java/com/epris/homepage/admin/dto/LoginRequestDto.java
src/main/java/com/epris/homepage/admin/dto/LoginResponseDto.java
src/main/java/com/epris/homepage/admin/dto/SignupRequestDto.java
src/main/java/com/epris/homepage/admin/dto/TokenRequestDto.java
src/main/java/com/epris/homepage/admin/dto/TokenResponseDto.java
src/main/java/com/epris/homepage/admin/repository/AdminRepository.java
src/main/java/com/epris/homepage/admin/repository/RefreshTokenRepository.java
src/main/java/com/epris/homepage/admin/service/AdminService.java
src/main/java/com/epris/homepage/admin/service/TokenService.java
src/main/java/com/epris/homepage/global/config/SecurityConfig.java
src/main/java/com/epris/homepage/global/config/TokenAuthFilter.java
src/main/java/com/epris/homepage/global/exception/ErrorCode.java
src/main/java/com/epris/homepage/global/jwt/JwtProperties.java
src/main/java/com/epris/homepage/global/jwt/TokenProvider.java

- 회원가입: 처음 한번만 가능
- 로그인: Jwt 사용해 액세스 토큰과 리프레시 토큰 발급 및 리프레시토큰 저장
- 로그아웃: 리프레시 토큰 삭제
- 액세스 토큰 재발급
- merge전에 application.yml 업데이트 해야함
- 액세스 토큰 재발급 부분 제대로 구현했는지 확인 한번 부탁드립니다.😭😭
#23

feat: Jwt 로그인 기능

---

build.gradle
src/main/java/com/epris/homepage/activity/network/controller/NetworkController.java
src/main/java/com/epris/homepage/activity/network/service/NetworkService.java

- 네트워크 수정 시 기존 이미지가 존재할 경우, 기존 이미지를 S3 버킷에서 삭제함.

refactor : 네트워크 수정 시 기존 이미지를 S3에서 삭제

---

src/main/java/com/epris/homepage/global/config/SecurityConfig.java

- SecurityFilterChain에서 cors설정을 수정하였습니다.

fix: cors 설정 수정

---

src/main/java/com/epris/homepage/activity/network/service/NetworkService.java

- 기존 이미지를 유지할 경우, 기존 이미지를 삭제하는 로직을 삭제함.

refactor :  네트워크 업데이트 로직 수정

---

src/main/java/com/epris/homepage/eprian/member/service/MemberService.java

- 학회원 정보를 업데이트 할 때, 프로필에 변경사항이 있는 경우에만 기존 프로필을 삭제하도록 변경.

refactor : 학회원 업데이트 로직 수정

---

src/main/java/com/epris/homepage/activity/corporate_project/service/CorporateProjectService.java
src/main/java/com/epris/homepage/global/config/SecurityConfig.java
src/main/java/com/epris/homepage/global/service/FileService.java

- 기존 이미지를 수정하지 않는 경우에 대한 로직을 추가함.

refactor : 기존 이미지를 전부 수정할 경우에 대한 로직 추가

---

src/main/java/com/epris/homepage/eprian/corporate_logo/service/LogoService.java

- 기존의 로고에 대한 수정이 없는 경우에 대한 로직을 추가함.

refactor : 기존의 로고를 모두 삭제할 경우에 대한 로직 추가

---

src/main/java/com/epris/homepage/eprian/member/service/MemberService.java

- 기존 회원의 프로필이 비어있지 않는 경우에 대한 조건문을 추가함.

refactor : 기존 회원 프로필이 비어있는지 확인하는 코드 추가

---

src/main/java/com/epris/homepage/activity/session/service/SessionService.java

- 기존 세션 이미지에서 변경할 이미지가 없는 경우, 파일 삭제는 이루어지지 않도록 조건을 추가함.

refactor : 기존 세션 이미지에서 삭제할 이미지가 없는 경우에 대한 조건 추가

---

src/main/java/com/epris/homepage/activity/network/service/NetworkService.java

- 기존 DB에 null 이 들어있는가를 확인하는 조건문을 수정함.

refactor : null 여부 확인 코드 수정

---

src/main/java/com/epris/homepage/eprian/member/controller/MemberController.java
src/main/java/com/epris/homepage/eprian/member/service/MemberService.java
src/main/java/com/epris/homepage/global/exception/ErrorCode.java

- 기수별 모든 학회원 삭제 기능 구현
- 학회원 삭제 후 해당 기수 정보도 삭제

feat : 기수별 전체 학회원 삭제 기능

---

src/main/java/com/epris/homepage/activity/network/service/NetworkService.java
src/main/java/com/epris/homepage/global/exception/ErrorCode.java

- request로 들어온 이미지 url이 null인 경우, 예외 발생.

exception : 이미지 url로 null이 들어오면 예외 발생

---

src/main/java/com/epris/homepage/global/exception/ApiExceptionHandler.java

- dto의 @Valid 유효성 체크를 위한 예외 처리를 구현함.

exception : @Valid 유효성 체크 예외 처리

---

src/main/java/com/epris/homepage/activity/network/controller/NetworkController.java
src/main/java/com/epris/homepage/activity/network/dto/NetworkReqeustDto.java
src/main/java/com/epris/homepage/activity/network/service/NetworkService.java
src/main/java/com/epris/homepage/global/exception/ErrorCode.java
src/main/java/com/epris/homepage/global/service/FileService.java

- `null`과 `""`, `" "`에 대해 모두 검사하도록 조건문을 수정함.
- request dto로 `null`, `""`, `" "` 이 들어오는 필드에 대해 예외가 발생하도록 처리함.

refactor : 조건문 수정, 요청 파라미터의 validation 체크

---

src/main/java/com/epris/homepage/activity/corporate_project/controller/CorporateProjectController.java
src/main/java/com/epris/homepage/activity/corporate_project/dto/CorporateProjectRequestDto.java

- request dto로 빈 값이 들어오는 경우 예외를 발생시킴.
- `null`, `""`, `" "`

refactor : 요청 파라미터의 validation 체크

---

src/main/java/com/epris/homepage/activity/corporate_project/dto/CorporateProjectRequestDto.java

- list에 값이 들어오는지를 확인하기 위해 @NotEmpty를 적용함.

refactor : @NotEmpty 적용으로 수정

---

src/main/java/com/epris/homepage/activity/session/dto/SessionRequestDto.java

- 요청 파라미터의 validation 체크를 위한 @NotEmpty를 적용함.

refactor : validation @NotEmpty 적용

---

src/main/java/com/epris/homepage/activity/corporate_project/dto/CorporateProjectRequestDto.java
src/main/java/com/epris/homepage/activity/session/dto/SessionRequestDto.java
src/main/java/com/epris/homepage/global/dto/ImageRequestDto.java
src/main/java/com/epris/homepage/global/dto/ImageUrl.java

- 리스트 자체에 대해서도 빈 값이 들어오지 않도록 함.
- 동시에 리스트 내 각각의 요소에 대해서 빈 값을 허용하지 않도록 validation 체크를 추가함.
- `null`, `""`, `" "`

refactor : 리스트 내 요소에 대한 validation 체크

---

src/main/java/com/epris/homepage/eprian/member/dto/MemberRequestDto.java

- String 을 제외한 필드에 대한 validation 체크를 해제함.

fix : validation 수정

---

src/main/java/com/epris/homepage/global/config/SecurityConfig.java

fix : corsConfig 수정

---

src/main/java/com/epris/homepage/admin/service/AdminService.java

feat: 리프레시토큰 유효기간 7일로 변경
